# Base image 
FROM python:3.10-slim

# Setting working directory
WORKDIR /app

# Copy Dependency list
COPY requirements.txt .

# Install Dependencies
RUN pip install --no-cache-dir -r requirements.txt

#Copy application code
COPY . .

#Expose port
EXPOSE 8000

# Start FastAPI server

CMD [ "uvicorn","inference_api:app","--host","0.0.0.0","--port","8000" ]

